### ISSUE TITLE
ModuleNotFoundError: No module named 'IPython'

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/DistributionOfWealthMPC#8]
On `master` in a fresh virtual environment, first installing requirements:

`$ pip install -r requirements.txt`

Then trying to `do_min`....

```
$ python do_min.py 
Traceback (most recent call last):
  File "do_min.py", line 21, in <module>
    exec(open('cstwMPC_MAIN.py').read())
  File "<string>", line 53, in <module>
ModuleNotFoundError: No module named 'IPython'
```

**Comment by sbenthall** [comment]
`$ pip install IPython` fixes this.

But then `do_min` gives me this error:

```
$ python do_min.py 
Traceback (most recent call last):
  File "do_min.py", line 21, in <module>
    exec(open('cstwMPC_MAIN.py').read())
  File "<string>", line 55, in <module>
ModuleNotFoundError: No module named 'SetupParamsCSTW'
```

**Comment by sbenthall** [comment]
Ah -- the docs recommend running in Spyder (not a good idea) or command line using `ipython`, which I suppose has a different default python paths that looks at the local file system. It's running now.

**Comment by sbenthall** [comment]
fixed with https://github.com/econ-ark/DistributionOfWealthMPC/commit/2a72f274bc70514c7f0498b60610413405316b8b
